[project]
name = "api-monitor"
version = "0.1.0"
description = "API Monitor Backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "motor",
    "apscheduler",
    "httpx",
    "pydantic",
    "pydantic-settings",
    "python-dotenv"
]